import type { Metadata } from "next";
import { Outfit, Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "../components/web/theme-provider";
import Navbar from "../components/web/Navbar";
import { Toaster } from "sonner";
import QueryProvider from "@/components/QueryProvider";

const ralewayHeading = Raleway({ subsets: ['latin'], variable: '--font-heading' });

const outfit = Outfit({ subsets: ['latin'], variable: '--font-sans' });


export const metadata: Metadata = {
  title: "AutoTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", outfit.variable, ralewayHeading.variable)}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
              <Navbar/>
          <main className="mt-10 mb-30 w-full px-4 md:px-6 lg:px-8">
            {children}
          </main>
                <Toaster
            duration={3000}
            closeButton
            expand

          />
        </ThemeProvider>
        </QueryProvider>
    


      </body>
    </html>
  );
}
