import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";


const notoSans = Noto_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "AutoTrack",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${notoSans.variable} antialiased mx-20`}
      >
        <Navbar/>
        <main className="mt-20 mb-50">
        {children}
        </main>

      </body>
    </html>
  );
}
